name: demo
run-name: Demos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-demo:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build demo
        run: yarn build:demo

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

  # Deployment job only on main branch
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    needs: build-demo
    if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
